#!/bin/bash
# init-research-profile.sh — Overlay research profile
# Usage: bash init-research-profile.sh [project-root]
# Run after init-skeleton.sh to add research-project-specific structure

set -euo pipefail

PROJECT_ROOT="${1:-.}"
cd "$PROJECT_ROOT"

CREATED=()
SKIPPED=()

create_file() {
    local filepath="$1"
    local content="$2"
    mkdir -p "$(dirname "$filepath")"
    if [ -f "$filepath" ]; then
        SKIPPED+=("$filepath")
    else
        echo "$content" > "$filepath"
        CREATED+=("$filepath")
    fi
}

ensure_dir() {
    mkdir -p "$1"
}

# ============================================================
# 1. Report & strategy directories
# ============================================================
ensure_dir "docs/reports/weekly"
ensure_dir "docs/reports/worktree"
ensure_dir "docs/plans"
ensure_dir "docs/strategy/decisions"
ensure_dir "docs/strategy/meetings"
ensure_dir "docs/strategy/related-work"

create_file "docs/strategy/vision.md" '# Vision

<!-- One-paragraph description of the project'"'"'s long-term vision -->
'

create_file "docs/strategy/roadmap.md" '# Roadmap

## Current Phase

<!-- What phase is the project in? -->

## Milestones

| Milestone | Target Date | Status |
|-----------|------------|--------|
<!-- Fill in milestones -->
'

create_file "docs/strategy/decisions/log.md" '# Decision Log

Record key architectural and strategic decisions.

## Format

```markdown
## YYYY-MM-DD: Decision Title

**Context**: why this decision was needed
**Decision**: what was decided
**Alternatives considered**: what else was evaluated
**Consequences**: what this implies going forward
```

---
<!-- Append decisions below -->
'

# ============================================================
# 2. Scripts subdirectory structure (research projects)
# ============================================================
ensure_dir "scripts/training"
ensure_dir "scripts/benchmark"
ensure_dir "scripts/data"
ensure_dir "scripts/model"
ensure_dir "scripts/infra"
ensure_dir "scripts/analysis"
ensure_dir "scripts/monitoring"

# ============================================================
# 3. Experiment registry (YAML-based, managed by exp-registry CLI)
# ============================================================
ensure_dir "docs/experiment-registry/registry"

create_file "docs/experiment-registry/README.md" '# Experiment Registry

Experiments are managed via the `exp-registry` CLI tool (`pip install exp-registry`).

## Quick Start

```bash
# Register a new experiment
exp register --name exp01a --hypothesis "..." --config "..."

# List all experiments
exp list

# Update experiment status
exp update exp01a --status completed --results "metric=value"
```

## Directory Structure

- `registry/` — YAML files, one per experiment (auto-generated by CLI)

## YAML Format

```yaml
name: exp01a
hypothesis: "..."
status: planned | running | completed | abandoned
config:
  model: ...
   ...
results:
  metric_1: value
  metric_2: value
notes: |
  Free-form notes
```'

# ============================================================
# 4. Domain expert agent scaffold
# ============================================================
create_file ".claude/agents/domain-expert.md" '---
name: domain-expert
description: <!-- Fill in: domain expertise description, e.g. "XX framework integration and debugging expert" -->
model: opus
memory: project
permissionMode: plan
tools:
  - Read
  - Grep
  - Glob
---

# Domain Expert

## Role

<!-- Fill in: what is this agent'"'"'s area of expertise -->

## When to Use

<!-- Fill in: what scenarios should trigger this agent -->

## How It Works

### 1. Receive Question

Get domain-related technical questions from the parent workflow.

### 2. Research Code

Focus directories and files:
<!-- Fill in: list directories this agent should focus on -->

### 3. Output Suggestions

Output format follows the planner agent standard format.

## Domain Knowledge

<!-- Fill in: key domain constraints, interface contracts, historical lessons -->'

# ============================================================
# 5. Paper Results Manifest (single source of truth for paper numbers)
# ============================================================
ensure_dir "docs/paper-results"

create_file "docs/paper-results/README.md" '# Paper Results Manifest

`results.yaml` is the only source of truth for benchmark numbers that enter the
paper. Raw benchmark outputs remain in `outputs/`, and experiment history
remains in `docs/experiment-registry/registry/`; this directory is the narrow
paper-facing layer.

## Three-tier sources of truth

1. **Raw outputs** (`outputs/`) — evidence only, never cited directly in paper
2. **Experiment registry** (`docs/experiment-registry/registry/*.yaml`) — full
   history, may contain stale / legacy / diagnostic / canonical entries
3. **Paper manifest** (`docs/paper-results/results.yaml`) — only canonical
   numbers allowed into paper tables and prose

## Workflow

```bash
# Validate manifest schema and that source paths exist
python3 scripts/benchmark/validate_paper_results.py

# Regenerate paper/generated/results_macros.tex from manifest
python3 scripts/benchmark/generate_paper_results.py
```

Paper tables and paragraphs should reference the generated macros rather than
hand-written numbers.

## Entry schema

Each `results` entry must include at minimum:

```yaml
- paper_key: "main_table.method_a.benchmark_x"  # macro lookup key
  exp_id: exp01a                                # registry pointer
  benchmark: benchmark_x
  eval_mode: <mode>                             # e.g. agent / direct / think
  value: 73.50
  correct: 1234
  total: 1678
  source_registry: docs/experiment-registry/registry/exp01a.yaml
  source_output: outputs/exp01a/benchmark_x/results.json
  status: canonical
  date: YYYY-MM-DD
  notes: |
    Free-form audit notes
```

Registry may keep multiple historical numbers; manifest must pick exactly one
canonical number per `paper_key`. When manifest and registry diverge, manifest
is the paper-facing truth and the divergence must be explained in `notes`.'

create_file "docs/paper-results/results.yaml" '# Paper Results Manifest
# Single source of truth for benchmark numbers entering the paper.
# Run scripts/benchmark/validate_paper_results.py before commits.

results:
  # - paper_key: "main_table.method_a.benchmark_x"
  #   exp_id: exp01a
  #   benchmark: benchmark_x
  #   eval_mode: <mode>
  #   value: 0.0
  #   correct: 0
  #   total: 0
  #   source_registry: docs/experiment-registry/registry/exp01a.yaml
  #   source_output: outputs/exp01a/benchmark_x/results.json
  #   status: canonical
  #   date: YYYY-MM-DD
  #   notes: ""

# NOTE: new entries must be inserted before any `derived:` block.
# Anything after `derived:` is ignored by the macro generator.'

create_file "scripts/benchmark/validate_paper_results.py" '#!/usr/bin/env python3
"""Validate docs/paper-results/results.yaml schema and source paths.

Checks:
- Each entry has required fields (paper_key, exp_id, benchmark, value, ...)
- source_registry and source_output paths exist
- paper_key uniqueness
- value matches correct / total when both are integers

Stub generated by init-project skill. Extend per project schema.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

MANIFEST = Path("docs/paper-results/results.yaml")
REQUIRED_FIELDS = (
    "paper_key",
    "exp_id",
    "benchmark",
    "value",
    "source_registry",
    "status",
    "date",
)


def main() -> int:
    if not MANIFEST.exists():
        print(f"[error] {MANIFEST} not found", file=sys.stderr)
        return 1

    data = yaml.safe_load(MANIFEST.read_text()) or {}
    entries = data.get("results") or []
    if not entries:
        print(f"[warn] {MANIFEST} has no results entries")
        return 0

    errors: list[str] = []
    seen_keys: set[str] = set()

    for idx, entry in enumerate(entries):
        prefix = f"entry[{idx}]"
        if not isinstance(entry, dict):
            errors.append(f"{prefix}: not a mapping")
            continue
        for field in REQUIRED_FIELDS:
            if field not in entry:
                errors.append(f"{prefix}: missing field {field!r}")
        key = entry.get("paper_key")
        if key in seen_keys:
            errors.append(f"{prefix}: duplicate paper_key {key!r}")
        elif key:
            seen_keys.add(key)
        for path_field in ("source_registry", "source_output"):
            src = entry.get(path_field)
            if src and not Path(src).exists():
                errors.append(f"{prefix}: {path_field} {src!r} does not exist")

    if errors:
        print("[fail] manifest validation errors:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 1

    print(f"[ok] {len(entries)} entries validated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'

create_file "scripts/benchmark/generate_paper_results.py" '#!/usr/bin/env python3
"""Generate paper/generated/results_macros.tex from results.yaml.

Each manifest entry produces a LaTeX macro:

    \\providecommand{\\Result<PaperKey>}{<value>}

Paper tables and prose should reference these macros instead of hand-written
numbers. Stub generated by init-project skill.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

MANIFEST = Path("docs/paper-results/results.yaml")
OUTPUT = Path("paper/generated/results_macros.tex")


def _macro_name(paper_key: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", paper_key)
    return "Result" + "".join(p.capitalize() for p in parts if p)


def main() -> int:
    if not MANIFEST.exists():
        print(f"[error] {MANIFEST} not found", file=sys.stderr)
        return 1
    data = yaml.safe_load(MANIFEST.read_text()) or {}
    entries = data.get("results") or []
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "% Auto-generated from docs/paper-results/results.yaml",
        "% DO NOT EDIT BY HAND — run scripts/benchmark/generate_paper_results.py",
        "",
    ]
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        key = entry.get("paper_key")
        value = entry.get("value")
        if key is None or value is None:
            continue
        lines.append(f"\\providecommand{{\\{_macro_name(key)}}}{{{value}}}")
    lines.append("")
    OUTPUT.write_text("\n".join(lines))
    print(f"[ok] wrote {len(entries)} macros to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'

# ============================================================
# 6. Append research-related content to AGENTS.md
# (CLAUDE.md stays as a thin @AGENTS.md stub — AGENTS.md is the single
#  source of truth for both CC and Codex / external runtimes.)
# ============================================================
if [ -f "AGENTS.md" ]; then
    # Check if research profile marker already exists
    if ! grep -q "<!-- research-profile -->" "AGENTS.md" 2>/dev/null; then
        cat >> "AGENTS.md" << 'RESEARCH_EOF'

<!-- research-profile -->

## Experiment Registry

Experiments are tracked via the `exp-registry` CLI (`pip install exp-registry`). One YAML file per experiment under `docs/experiment-registry/registry/`. Treat the registry as the full experiment history; the paper manifest (`docs/paper-results/results.yaml`) picks the canonical subset that goes into the paper.

## Project Strategy

Strategy documents live in `docs/strategy/`:

| Document | Purpose |
|----------|---------|
| `vision.md` | Long-term project vision |
| `roadmap.md` | Milestones and current phase |
| `decisions/log.md` | Architectural and strategic decision records |
| `meetings/` | Meeting notes (named `YYYY-MM-DD.md`) |
| `related-work/` | Related work analysis and survey |

Read these when reviewing project direction, doing alignment checks, or preparing for milestone-level discussions.
RESEARCH_EOF
        CREATED+=("AGENTS.md (appended research profile)")
    else
        SKIPPED+=("AGENTS.md (research profile already exists)")
    fi
fi

# ============================================================
# Output summary
# ============================================================
echo ""
echo "=========================================="
echo "  research profile overlay complete"
echo "=========================================="
echo ""

if [ ${#CREATED[@]} -gt 0 ]; then
    echo "✓ Created/modified ${#CREATED[@]} files:"
    for f in "${CREATED[@]}"; do
        echo "  + $f"
    done
fi

if [ ${#SKIPPED[@]} -gt 0 ]; then
    echo ""
    echo "⊘ Skipped ${#SKIPPED[@]} existing files:"
    for f in "${SKIPPED[@]}"; do
        echo "  - $f"
    done
fi
